services:
  app:
    image: ghcr.io/vert-sh/vert:latest
    container_name: VERT
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${{PORT}}
      - PUB_HOSTNAME=${{PUB_HOSTNAME}}
    volumes:
      - app_data:/data

volumes:
  app_data:
